In [1]:
import numpy as np
from numpy import linalg as LA

In [4]:
# define matrix
M = np.array([[0, 1, 1], [-3, 2,3], [1, 1, 0]])
print(M)

[[ 0  1  1]
 [-3  2  3]
 [ 1  1  0]]


In [5]:
# compute eigenvalues and eigenvectors
eigenVal, eigenVec = LA.eig(M)
print(eigenVal)
print(eigenVec)


[-1.  1.  2.]
[[ 1.68783755e-16 -7.07106781e-01  5.77350269e-01]
 [-7.07106781e-01  1.15377761e-15  5.77350269e-01]
 [ 7.07106781e-01 -7.07106781e-01  5.77350269e-01]]


In [7]:
# get eigenspace basis vectors
v1 = eigenVec[:, 0]
v2 = eigenVec[:, 1]
print(v1)
print(v2)

[ 1.68783755e-16 -7.07106781e-01  7.07106781e-01]
[-7.07106781e-01  1.15377761e-15 -7.07106781e-01]
