In [2]:
import numpy as np
from numpy import linalg as LA

In [5]:
# define matrix
A = np.array([[-1, 3, -5], [-1, -2,2], [0, 1, -3]])
print(A)

[[-1  3 -5]
 [-1 -2  2]
 [ 0  1 -3]]


In [7]:
# compute eigenvalues and eigenvectors
eigenVal, eigenVec = LA.eig(A)
print(eigenVal)


[-1.99997992+0.00000000e+00j -2.00001004+1.73889314e-05j
 -2.00001004-1.73889314e-05j]


In [4]:
# get eigenspace basis vectors
v1 = eigenVec[:, 0]
v2 = eigenVec[:, 1]
print(v1)
print(v2)

[ 7.07106781e-01+0.j -5.18211926e-16+0.j  7.07106781e-01+0.j]
[0.31622777+0.15811388j 0.15811388+0.47434165j 0.79056942+0.j        ]
